# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6cf4e05bf7e2cd0441da6acc9a270e93"
name = "checkout-ui"
handle = "checkout-ui-333"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "vastadev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
